<div id="content">
    <ul id="items">
        <?php foreach($this->products as $key => $value)
        { ?>
            <li class="item">
                <h2><?php echo $value['productTitle']; ?></h2>
                <a href="/admin/product/delete/id/<?php echo $value['productId']; ?>">Verwijderen</a> - <a href="/admin/product/edit/id/<?php echo $value['productId']; ?>">Aanpassen</a>              
            </li>
        <?php
        }
        ?>
    </ul>
</div>