<div id="fp-cat-list">
    <h2><?php echo $this->translate('fp.cats'); ?></h2>
    <ul>
        <?php 
            foreach($this->cat as $cat)
            {
                ?>            
                <li><a href="/overview/viewcat/id/<?php echo $cat['categoryId']; ?>"><?php echo $cat['categoryName']; ?></a></li>
                <?php
            }
        ?>
    </ul>
</div>

<div id="fp-product-list">
    <h2><?php echo $this->translate('fp.products'); ?></h2>
    <ul>
         <?php 
            foreach($this->product as $product)
            {
                ?>            
                <li><a href="/overview/viewproduct/id/<?php echo $product['productId']; ?>"><?php echo $product['productTitle']; ?></a></li>
                <?php
            }
        ?>      
    </ul>
</div>