<div id="content">
    
   <ul id="items">
        <?php foreach($this->basket as $key => $value)
        { ?>
            <li class="item">
                <figure>
                    <img class="thumb" src="/upload/<?php echo $value['photo']; ?>" alt="<?php echo $value['title']; ?>" />                                     
                </figure>
                <h2><?php echo $value['title']; ?></h2>
                <p>Aantal <?php echo $value['count']; ?> - Totaalprijs <?php echo $value['price']; ?></p>
            </li>
        <?php
        }
        ?>
    </ul>
    
     <a href="/basket/emptybasket/"><?php echo $this->translate('emptybasket'); ?></a> - <a href="/order"><?php echo $this->translate('order'); ?></a>              

</div>