<div id="content">
    
   <ul id="items">
        <?php foreach($this->basket as $key => $value)
        { ?>
            <li class="item">
                <figure>
                    <img src="/upload/<?php echo $value['photoName'] . '.' . $value['photoType'] . '';?>" alt="<?php echo $value['title']; ?>" />
                    <figcaption>Teaser....</figcaption>                  
                </figure>
                <h2><?php echo $value['title']; ?></h2>
                <p><?php echo $value['count']; ?></p>
                <p><?php echo $value['price']; ?></p>
                
                <a href="/basket/emptybasket/"><?php echo $this->translate('emptybasket'); ?></a> - <a href="/order"><?php echo $this->translate('order'); ?></a>              
            </li>
        <?php
        }
        ?>
    </ul>
</div>