<div id="content">
    <ul id="items">
        <?php foreach($this->result as $result)
        {
            
        ?>
        <li class="item">
            <figure>
                <a href="/<?php echo $result['locale']; ?>/product/<?php echo $result['slug']; ?>">
                    <img class="thumb" src="/upload/<?php echo $result['photoName'] . '.' . $result['photoType'] . '';?>" alt="<?php echo $result['title']; ?>" />
                </a>
            </figure>
            <h2><?php echo $result['title']; ?></h2>
            <p><?php echo $result['teaser']; ?></p>
        <?php } ?>
        </li>
    </ul>
</div>