<div id="search-results">
    <ul>
        <?php foreach($this->result as $result)
        {
            
        ?>
        <li>
            <figure>
                <img src="http://placehold.it/250x150/ffffff" alt="placeholder" />
            </figure>
            <h2><?php echo $result['title']; ?></h2>
            <p><?php echo $result['teaser']; ?></p>
        <?php } ?>
        </li>
    </ul>
</div>