<!doctype>
<html>
    <head>
        <title>Eindwerk Dennis Dirksma - admin</title>
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
    </head>

    <div id="backgroundContainer">
        <div id="container">
            <header>
                
            </header>
            <?php echo $this->layout()->content; ?>
            
            <div id="clear">&nbsp;</div>
        </div>
    </div>
</html>