<!doctype>
<html>
    <head>
        <title>Eindwerk Dennis Dirksma</title>
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
    </head>

    <div id="backgroundContainer">
        <div id="container">
            <header>
                <nav>
                    <?php echo $this->navigation()->menu(); ?>
                </nav>
                <div id="search">
                    <?php echo $this->searchForm($this->searchForm); ?>
                </div>
            </header>
            <?php echo $this->layout()->content; ?>
            
            <div id="clear">&nbsp;</div>
        </div>
    </div>
</html>