<!doctype>
<html>
    <head>
        <title>Eindwerk Dennis Dirksma</title>
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <script src="/js/site.js"></script>
        <script src="/js/galleriffic/jquery.galleriffic.js"></script>
        <script src="/js/galleriffic/jquery.opacityrollover.js"></script>
    </head>

    <div id="backgroundContainer">
        <div id="container">
            <header>
                <section id="logo">
                    <h1><a href="/">Microsoft webshop, alle Microsoft producten, all Microsoft products</a></h1>
                    <h2><?php echo $this->translate('header.subtxt'); ?></h2>
                </section>
                <section id="login">
                    <h2><?php echo $this->translate('login.title'); ?></h2>
                    <?php echo $this->loginForm($this->loginForm); ?>
                </section>
                <div id="sub">
                    <nav>
                        <?php echo $this->navigation()->menu(); ?>
                    </nav>            
                    <section id="basket">
                        <p><?php echo $this->translate('basket.contains'); ?> <?php echo $this->basketItems; ?> <?php echo $this->translate('basket.item'); ?> <?php echo $this->translate('basket.total'); ?> &euro; 500,-</p>
                    </section>
                    <section id="search">
                        <?php echo $this->searchForm($this->searchForm); ?>
                    </section>
                </div>                   
            </header>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
            
            <div id="clear">&nbsp;</div>
        </div>
    </div>
</html>